name = "cardo-capital"
main = "workers/index.js"
compatibility_date = "2026-03-10"

kv_namespaces = [
  { binding = "USERS_KV", id = "0560a13ee4334d5597d59580c013cd19" },
  { binding = "SETTINGS_KV", id = "e9401fb1cea74d6990d793f9f384238a" }
]

vars = { ADMIN_KEY = "supersecretadminkey" }
